#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define PATH_MAX_SIZE 4096
#define CONTENT_NAME_MAX_SIZE 255

#define BUFFER_MAX_SIZE 1024000
#define BUFFERS_QUANTITY 2

#define PATH_SEPARATOR '/'
#define NULL_TERMINATOR '\0'

#endif